services:
  fundamental-metric:
    build:
      context: .
      tags: 
        - "fundamental-metrics:main"
    container_name: fundamental-metrics
    network_mode: host
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
