defaults:
  - metrics/clip@metrics.clip  # Load CLIP config
  - metrics/fid@metrics.fid    # Load FID config
  - metrics/inception@metrics.inception
  - _self_

device: cuda

metrics:
  clip:
    _target_: metrics.clip_score.CLIPSimilarity
    mode: text_image
    model_name: ViT-B/32

  fid:
    _target_: metrics.fid_score.FIDMetric
    feature: 2048
  
  inception:
    _target_: metrics.inception_score.InceptionScoreMetric